import {defineField, defineType} from 'sanity'

export const accommodationType = defineType({
  name: 'accommodation',
  title: 'Accommodation',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'rooms', title: 'Rooms'},
    {name: 'seo', title: 'SEO'},
    {name: 'settings', title: 'Settings'},
  ],
  fields: [
    defineField({name: 'name', title: 'Name', type: 'string', group: 'content', validation: (Rule) => Rule.required()}),
    defineField({name: 'slug', title: 'Slug', type: 'slug', group: 'content', options: {source: 'name', maxLength: 96}, validation: (Rule) => Rule.required()}),
    defineField({name: 'type', title: 'Type', type: 'string', group: 'content', options: {list: ['Hotel', 'Guesthouse', 'Lodge', 'Camp', 'Heritage stay', 'Resort']}}),
    defineField({name: 'location', title: 'Location', type: 'location', group: 'content'}),
    defineField({name: 'shortDescription', title: 'Short description', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'description', title: 'Full description', type: 'portableContent', group: 'content'}),
    defineField({name: 'pricing', title: 'Pricing', type: 'pricing', group: 'content'}),
    defineField({name: 'heroImage', title: 'Hero image', type: 'mediaImage', group: 'content'}),
    defineField({name: 'gallery', title: 'Gallery', type: 'array', of: [{type: 'mediaImage'}], group: 'content'}),
    defineField({name: 'video', title: 'Video', type: 'videoEmbed', group: 'content'}),
    defineField({name: 'amenities', title: 'Amenities', type: 'array', of: [{type: 'string'}], options: {layout: 'tags'}, group: 'content'}),
    defineField({name: 'highlights', title: 'Highlights (trust bullets)', type: 'array', of: [{type: 'string'}], group: 'content', description: '4–6 short selling points shown prominently on the detail page.'}),
    defineField({name: 'included', title: 'What is included', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'excluded', title: 'What is NOT included', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'cancellationPolicy', title: 'Cancellation policy', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'houseRules', title: 'House rules', type: 'array', of: [{type: 'string'}], group: 'rooms'}),
    defineField({name: 'roomTypes', title: 'Room types', type: 'array', of: [{type: 'roomType'}], group: 'rooms'}),
    defineField({name: 'checkInTime', title: 'Check-in time', type: 'string', group: 'rooms'}),
    defineField({name: 'checkOutTime', title: 'Check-out time', type: 'string', group: 'rooms'}),
    defineField({name: 'faqs', title: 'FAQs', type: 'array', of: [{type: 'faqItem'}], group: 'seo'}),
    defineField({name: 'seo', title: 'SEO', type: 'seoFields', group: 'seo'}),
    defineField({name: 'rating', title: 'Rating', type: 'number', group: 'settings', validation: (Rule) => Rule.min(0).max(5)}),
    defineField({name: 'reviewCount', title: 'Review count', type: 'number', group: 'settings'}),
    defineField({name: 'featured', title: 'Featured', type: 'boolean', initialValue: false, group: 'settings'}),
    defineField({name: 'bookable', title: 'Bookable separately', type: 'boolean', initialValue: true, group: 'settings'}),
    defineField({name: 'status', title: 'Status', type: 'string', initialValue: 'draft', group: 'settings', options: {list: ['draft', 'live', 'hidden']}}),
  ],
  preview: {
    select: {title: 'name', subtitle: 'location.city', media: 'heroImage'},
  },
})
