import {defineField, defineType} from 'sanity'

export const packageType = defineType({
  name: 'package',
  title: 'Packages',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'itinerary', title: 'Itinerary'},
    {name: 'inventory', title: 'Linked services'},
    {name: 'seo', title: 'SEO'},
    {name: 'settings', title: 'Settings'},
  ],
  fields: [
    defineField({name: 'title', title: 'Title', type: 'string', group: 'content', validation: (Rule) => Rule.required()}),
    defineField({name: 'slug', title: 'Slug', type: 'slug', group: 'content', options: {source: 'title', maxLength: 96}, validation: (Rule) => Rule.required()}),
    defineField({name: 'subtitle', title: 'Subtitle', type: 'string', group: 'content'}),
    defineField({name: 'summary', title: 'Summary', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'description', title: 'Full description', type: 'portableContent', group: 'content'}),
    defineField({name: 'destination', title: 'Destination', type: 'reference', to: [{type: 'destination'}], group: 'content'}),
    defineField({name: 'region', title: 'Region label', type: 'string', group: 'content'}),
    defineField({name: 'days', title: 'Days', type: 'number', group: 'content', validation: (Rule) => Rule.required().min(1)}),
    defineField({name: 'nights', title: 'Nights', type: 'number', group: 'content', validation: (Rule) => Rule.min(0)}),
    defineField({name: 'difficulty', title: 'Difficulty', type: 'string', group: 'content', options: {list: ['Easy', 'Moderate', 'Strenuous']}}),
    defineField({name: 'season', title: 'Season', type: 'string', group: 'content'}),
    defineField({name: 'pricing', title: 'Pricing', type: 'pricing', group: 'content'}),
    defineField({name: 'heroImage', title: 'Hero image', type: 'mediaImage', group: 'content'}),
    defineField({name: 'gallery', title: 'Gallery', type: 'array', of: [{type: 'mediaImage'}], group: 'content'}),
    defineField({name: 'video', title: 'Video', type: 'videoEmbed', group: 'content'}),
    defineField({name: 'highlights', title: 'Highlights', type: 'array', of: [{type: 'string'}], options: {layout: 'tags'}, group: 'content'}),
    defineField({name: 'included', title: 'Included', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'excluded', title: 'Excluded', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'itineraryDays', title: 'Day-by-day itinerary', type: 'array', of: [{type: 'itineraryDay'}], group: 'itinerary'}),
    defineField({name: 'accommodations', title: 'Linked accommodations', type: 'array', of: [{type: 'reference', to: [{type: 'accommodation'}]}], group: 'inventory'}),
    defineField({name: 'vehicles', title: 'Linked vehicles', type: 'array', of: [{type: 'reference', to: [{type: 'vehicle'}]}], group: 'inventory'}),
    defineField({name: 'guides', title: 'Linked guides', type: 'array', of: [{type: 'reference', to: [{type: 'guide'}]}], group: 'inventory'}),
    defineField({name: 'restaurants', title: 'Linked restaurants', type: 'array', of: [{type: 'reference', to: [{type: 'restaurant'}]}], group: 'inventory'}),
    defineField({name: 'faqs', title: 'FAQs', type: 'array', of: [{type: 'faqItem'}], group: 'seo'}),
    defineField({name: 'seo', title: 'SEO', type: 'seoFields', group: 'seo'}),
    defineField({name: 'rating', title: 'Rating', type: 'number', group: 'settings', validation: (Rule) => Rule.min(0).max(5)}),
    defineField({name: 'reviewCount', title: 'Review count', type: 'number', group: 'settings', validation: (Rule) => Rule.min(0)}),
    defineField({name: 'spotsLeft', title: 'Seats left', type: 'number', group: 'settings', validation: (Rule) => Rule.min(0)}),
    defineField({name: 'featured', title: 'Featured', type: 'boolean', initialValue: false, group: 'settings'}),
    defineField({name: 'showOnHome', title: 'Show on homepage', type: 'boolean', initialValue: false, group: 'settings'}),
    defineField({name: 'priority', title: 'Display priority', type: 'number', initialValue: 100, group: 'settings'}),
    defineField({name: 'status', title: 'Status', type: 'string', initialValue: 'draft', group: 'settings', options: {list: ['draft', 'live', 'hidden']}}),
  ],
  preview: {
    select: {title: 'title', subtitle: 'region', media: 'heroImage'},
  },
})
